# For Andor Zyla

# CAMERA SENSOR PIXEL SIZE UM
CAM_PX_UM = 6.5

# CAMERA SENSOR TOTAL PIXELS
CAM_X_PX = 2048
CAM_Y_PX = 2048

# PIXEL_SIZE_UM = CAMERA_PIXEL_SIZE_UM / MAG
# FOV_WIDTH = CAM_X_PX * PIXEL_SIZE_UM
# PIXELS_TO_MM = IMG_PIXELS_TO_MM / MAG
